apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: foundation-models-template
  annotations:
    scenarios.ai.sap.com/used-for: "foundation-models"
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: prompt
          - name: temperature
          - name: max_tokens
      container:
        image: docker.io/saplabs/foundation-models-runner:latest
        command: [ "python3" ]
        args:
          - /app/run.py
          - --prompt
          - "{{inputs.parameters.prompt}}"
          - --temperature
          - "{{inputs.parameters.temperature}}"
          - --max_tokens
          - "{{inputs.parameters.max_tokens}}"
