apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: testfoundation-models-template
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: busybox
        command: ["echo"]
        args: ["Hello from testfoundation-models-template!"]
